# Tensors

[Link to the related offical tutorial](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html). Based by Update:: Jan 24, 2025

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to [NumPy’s](https://numpy.org/) ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see [Bridge with NumPy](https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autogradsection). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!


Tensors can be initialized in various ways. Take a look at the following examples:

- Directly from data: Tensors can be created directly from data. The data type is automatically inferred.

- From a NumPy array: Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).
- From another tensor: The new tensor retains the properties (`shape`, `datatype`) of the argument tensor, unless explicitly overridden.
- With random or constant values: `shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.


In [ ]:
import torch
import numpy as np

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
type(x_data), x_data


(torch.Tensor,
 tensor([[1, 2],
         [3, 4]]))

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6370, 0.0018],
        [0.8137, 0.9191]]) 



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5580, 0.9137, 0.3925],
        [0.2729, 0.1664, 0.1025]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the CPU and [Accelerator](https://pytorch.org/docs/stable/torch.html#accelerators) such as CUDA, MPS, MTIA, or XPU. If you are using Colab, allocate an accelerator by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using `.to` method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [ ]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

torch.accelerator.is_available()

False

### Standard numpy-like indexing and slicing

**Standard numpy-like indexing and slicing:**

In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors

**Joining tensors** You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joining operator that is subtly different from `torch.cat`.

In [ ]:
print(tensor)

print('\n', '-' * 10, '\n')

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

print('\n')
t0 = torch.cat([tensor, tensor])
print(t0)

print('\n')
t0 = torch.cat([tensor, tensor], dim = 1)
print(t0)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

 ---------- 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetic operations

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor

print('Tensore: \n', tensor)
print('\n')
print('Transpose: \n', tensor.T)
print('\n', '-' * 10, '\n')

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print('y1: \n', y1)
print('\n')
print('y2: \n', y2)
print('\n', '-' * 10, '\n')

y3 = torch.rand_like(y1)
print('y3: \n', y3)
print('\n')
r0 = torch.matmul(tensor, tensor.T, out=y3)
print('r0: \n', r0)
print('\n', '-' * 10, '\n')

# This computes the element-wise product. z1, z2, z3 will have the same value
print('Computes the element-wise product. \n')

z1 = tensor * tensor
print('z1: \n', z1)
print('\n')
z2 = tensor.mul(tensor)
print('z2: \n', z2)
print('\n')

z3 = torch.rand_like(tensor)
print('z3: \n', z3)
print('\n')
r1 = torch.mul(tensor, tensor, out=z3)
print('r1: \n', r1)
print('\n', '-' * 10, '\n')

Tensore: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Transpose: 
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

 ---------- 

y1: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


y2: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

 ---------- 

y3: 
 tensor([[0.0808, 0.6425, 0.9871, 0.7397],
        [0.1410, 0.2857, 0.3819, 0.2792],
        [0.6294, 0.4485, 0.6704, 0.4403],
        [0.5751, 0.1936, 0.0134, 0.8668]])


r0: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

 ---------- 

Computes the element-wise product. 

z1: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


z2: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],

### Single-element tensors

If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


## In-place operations

Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

> In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged



In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

## Tensor to NumPy array

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
print(type(t))
print('\n')
n = t.numpy()
print(f"n: {n}")
print(type(n))

t: tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


n: [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


A change in the tensor reflects in the NumPy array.

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


# NumPy array to Tensor

Changes in the NumPy array reflects in the tensor.

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
